# Generated by Django 4.1.7 on 2023-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0002_urun_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='seriNo',
            field=models.CharField(default='seri no bilinmiyor', max_length=7, verbose_name='Urunun seri numarasi'),
        ),
    ]
