# Generated by Django 4.1.7 on 2023-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0003_urun_serino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='seriNo',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Urunun seri numarasi'),
        ),
    ]
