# Generated by Django 4.1.7 on 2023-04-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0011_urun_satici'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.CharField(max_length=19, verbose_name='Hesap Numarasi')),
                ('cardOwner', models.CharField(max_length=50, verbose_name='Hesap Sahibi')),
                ('expiredMonthAndYear', models.CharField(max_length=5, verbose_name='Gecerlilik Suresi')),
                ('cvc', models.CharField(max_length=3, verbose_name='Guvenlik Kodu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
        ),
    ]
