# Generated by Django 4.1.7 on 2023-04-26 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0012_usercreditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Tarih')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunApp.usercreditcard', verbose_name='Islem Yapilan Kart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunApp.urun', verbose_name='Satin Alinan Urun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satin Alan Kisi')),
            ],
        ),
    ]
