# Generated by Django 4.1.7 on 2023-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0013_purchaselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darkMode', models.BooleanField(default=False, verbose_name='Karanlik Mod')),
            ],
        ),
    ]
