# Generated by Django 4.1.7 on 2023-07-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0013_purchaselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='eklenmeTarihi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='garanti',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='satici',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='seriNo',
        ),
    ]
