# Generated by Django 4.1.7 on 2023-07-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0014_remove_urun_eklenmetarihi_remove_urun_garanti_and_more'),
        ('urunApp', '0015_preferedtheme_user'),
    ]

    operations = [
    ]
