# Generated by Django 4.2 on 2023-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0017_reservation_delete_preferedtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mail Adresi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
