# Generated by Django 4.2 on 2023-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0018_reservation_email_reservation_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Adı'),
        ),
    ]
