# Generated by Django 4.2 on 2023-07-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0019_reservation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezervasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunApp.reservation', verbose_name='Rezervasyon Yapıldı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rezervasyonu Yapan Kişi')),
            ],
        ),
    ]
